// Maps cities from the CSV dataset to their respective Indian states
export const cityToState = {
  "Ahmedabad": "Gujarat",
  "Chennai": "Tamil Nadu",
  "Ludhiana": "Punjab",
  "Pune": "Maharashtra",
  "Delhi": "NCT of Delhi",
  "Mumbai": "Maharashtra",
  "Bangalore": "Karnataka",
  "Kolkata": "West Bengal",
  "Hyderabad": "Telangana",
  "Surat": "Gujarat",
  "Visakhapatnam": "Andhra Pradesh",
  "Ghaziabad": "Uttar Pradesh",
  "Jaipur": "Rajasthan",
  "Lucknow": "Uttar Pradesh",
  "Kanpur": "Uttar Pradesh",
  "Nagpur": "Maharashtra",
  "Indore": "Madhya Pradesh",
  "Thane": "Maharashtra",
  "Bhopal": "Madhya Pradesh",
  "Patna": "Bihar",
  "Vadodara": "Gujarat",
  "Agra": "Uttar Pradesh",
  "Nashik": "Maharashtra",
  "Faridabad": "Haryana",
  "Meerut": "Uttar Pradesh",
  "Rajkot": "Gujarat",
  "Varanasi": "Uttar Pradesh",
  "Srinagar": "Jammu & Kashmir",
  "Aurangabad": "Maharashtra",
  "Dhanbad": "Jharkhand",
  "Amritsar": "Punjab",
  "Allahabad": "Uttar Pradesh",
  "Ranchi": "Jharkhand",
  "Howrah": "West Bengal",
  "Coimbatore": "Tamil Nadu",
  "Jabalpur": "Madhya Pradesh",
  "Gwalior": "Madhya Pradesh",
  "Vijayawada": "Andhra Pradesh",
  "Jodhpur": "Rajasthan",
  "Madurai": "Tamil Nadu",
  "Raipur": "Chhattisgarh",
  "Kota": "Rajasthan",
  "Chandigarh": "Chandigarh",
  "Guwahati": "Assam",
  "Solapur": "Maharashtra",
  "Hubli-Dharwad": "Karnataka",
  "Bareilly": "Uttar Pradesh",
  "Moradabad": "Uttar Pradesh",
  "Mysore": "Karnataka",
  "Tiruchirappalli": "Tamil Nadu",
  "Tiruppur": "Tamil Nadu",
  "Dehradun": "Uttarakhand",
  "Mangalore": "Karnataka",
  "Bhubaneswar": "Odisha",
  "Cuttack": "Odisha",
};

export function getStateForCity(city) {
  return cityToState[city] || "Unknown";
}
